version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  nodeapp:
    #container_name: "cueh/6005_nosql"
    image: cueh/6005_nosql
    build: .
    ports:
      - "4242:4242"
    links:
      - "mongodb:mongo"
    depends_on:
      - "mongodb"
      
